replicaCount: 3
image:
  repository: 123456789012.dkr.ecr.ap-south-1.amazonaws.com/order-service
  tag: prod
containerPort: 8080
resources:
  requests: { cpu: 500m, memory: 1Gi }
  limits: { cpu: 1, memory: 2Gi }
autoscaling: { minReplicas: 3, maxReplicas: 6, targetCPUUtilizationPercentage: 70 }
domain: hyper-platform.com
environment: prod
dbPassword: prod-order-secret
secretProvider:
  objectName: order-service-db-password
