replicas: 1

minimumMasterNodes: 1

esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: false

resources:
  requests:
    cpu: 500m
    memory: 2Gi

  limits:
    cpu: 2
    memory: 4Gi

volumeClaimTemplate:
  accessModes:
    - ReadWriteOnce

  storageClassName: gp3

  resources:
    requests:
      storage: 50Gi

antiAffinity: "soft"

podDisruptionBudget:
  maxUnavailable: 1

service:
  type: ClusterIP

persistence:
  enabled: true